import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import LeftPanel from "@/components/LeftPanel";
import { ClerkProvider } from "@clerk/nextjs";
import ThemeProvider from "@/components/Themes/ThemeProvider";
import { cookies } from "next/headers";
import clsx from "clsx";
import TopPanel from "@/components/TopPanel";

const ibm = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Imaginify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get("theme")?.value;
  const curentStyle = clsx({
    light: theme === "light",
    dark: theme === "dark",
  });
  return (
    <ClerkProvider>
      <ThemeProvider currentTheme={theme!}>
        <html lang="en" className={curentStyle}>
          <body className={ibm.className}>
            <div className="w-full flex flex-col lg:flex-row relative">
              <TopPanel />
              <LeftPanel />
              <main className="w-full dark:bg-slate-800 px-12 py-9">
                {children}
              </main>
            </div>
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
